apiVersion: v1
kind: Pod
metadata:
  name: payment
  labels:
    tier: app
    name: payment
spec:
  containers:
    - name: payment
      imagePullPolicy: Always
      image: pavanreddy1219/payment:k8
      resources:
        requests:
          memory: "100Mi"
          cpu: "250m"
        limits:
          memory: "200Mi"
          cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: payment
spec:
  selector:
    tier: app
    name: payment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
