apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq
  labels:
    tier: backend
    name: rabbitmq
spec:
  containers:
    - name: rabbitmq
      image: rabbitmq
      imagePullPolicy: Always  # Added image pull policy
      resources:
        requests:
          memory: "100Mi"
          cpu: "250m"
        limits:
          memory: "500Mi"
          cpu: "1000m"
      ports:
        - containerPort: 5672  # Added container port for RabbitMQ
        - containerPort: 15672  # Added container port for RabbitMQ management UI

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    tier: backend
    name: rabbitmq
  ports:
    - protocol: TCP
      port: 5672  # Port for RabbitMQ
      targetPort: 5672
    - protocol: TCP
      port: 15672  # Port for RabbitMQ management UI
      targetPort: 15672
