apiVersion: v1
kind: Pod
metadata:
  name: ratings
  labels:
    tier: app
    name: ratings
spec:
  containers:
    - name: rating
      imagePullPolicy: Always
      image: pavanreddy1219/ratings:k8
      resources:
        requests:
          memory: "100Mi"
          cpu: "250m"
        limits:
          memory: "200Mi"
          cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: ratings
spec:
  selector:
    tier: app
    name: ratings 
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
