apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    tier: backend
    name: mongodb
spec:
  containers:
    - name: mongodb
      image: pavanreddy1219/mongodb:k8
      resources:
        requests:
          memory: "100Mi"
          cpu: "250m"
        limits:
          memory: "200Mi"
          cpu: "500m"
      ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    tier: backend
    name: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
