apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue-configmap  # Replace with your desired name
data:
  MONGO_URL: "mongodb://mongodb:27017/catalogue"  # Added quotes around the URL
---
apiVersion: v1
kind: Pod
metadata:
  name: catalogue
  labels:
    tier: app
    name: catalogue
spec:
  containers:
    - name: catalogue
      imagePullPolicy: Always
      image: pavanreddy1219/catalogue:k8
      envFrom:  # Corrected the field name
        - configMapRef:  # Corrected the field name
            name: catalogue-configmap
      resources:
        requests:
          memory: "100Mi"
          cpu: "250m"
        limits:
          memory: "200Mi"
          cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
spec:
  selector:
    tier: app
    name: catalogue
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
