apiVersion: v1
kind: Pod
metadata:
  name: catalogue
  labels:
    tier: app
    name: catalogue
spec:
  containers:
    - name: catalogue
      imagePullPolicy: Always  # Corrected the field name and indentation
      image: pavanreddy1219/catalogue:k8
      resources:
        requests:
          memory: "100Mi"
          cpu: "250m"
        limits:
          memory: "200Mi"
          cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: catalogue-service
spec:
  selector:
    tier: app
    name: catalogue
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
