apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
data:
  MONGO_URL: "mongodb://mongodb:27017/users"
  REDIS_HOST: "redis"
---
apiVersion: v1
kind: Pod
metadata:
  name: user
  labels:
    tier: app
    name: user
spec:
  containers:
    - name: user
      imagePullPolicy: Always
      image: pavanreddy1219/user:k8
      env:
        - name: MONGO_URL
          valueFrom:
            configMapKeyRef:
              name: user-config
              key: MONGO_URL
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: user-config
              key: REDIS_HOST
      resources:
        requests:
          memory: "100Mi"
          cpu: "250m"
        limits:
          memory: "200Mi"
          cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  selector:
    tier: app
    name: user
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
