apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    tier: backend
    name: redis
spec:
  containers:
    - name: redis
      image: redis
      resources:
        requests:
          memory: "100Mi"
          cpu: "250m"
        limits:
          memory: "200Mi"
          cpu: "500m"
      ports:
        - containerPort: 6379
   