apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    tier: backend
    name: redis
spec:
  containers:
    - name: redis
      image: redis
      resources:
        requests:
          memory: "100Mi"
          cpu: "250m"
        limits:
          memory: "200Mi"
          cpu: "500m"
      ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
   tier: backend
   name: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379