apiversion: v1
kind: pod 
metadata:
  name: web
  labels:
    tier: frontend
    purpose: web
spec:
  containers:
    - name: web
      image: pavanreddy1219/web:k8
      ports:
      - containerport: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: LoadBalancer
  selector:
      tier: frontend
      purpose: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80