apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    tier: frontend
    name: web
spec:
  containers:
    - name: web
      imagePullPolicy: Always  # Corrected the field name
      image: pavanreddy1219/web:k8
      resources:
        requests:
          memory: "100Mi"
          cpu: "250m"
        limits:
          memory: "200Mi"
          cpu: "500m"
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: LoadBalancer
  selector:
      tier: frontend
      name: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
