apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    tier: frontend
    purpose: web
spec:
  containers:
    - name: web
      imagepullpolicy: always
      image: pavanreddy1219/web:k8
      resources:
      requests:
        memory: "100Mi"
        cpu: "250m"
      limits:
        memory: "200Mi"
        cpu: "500m"
      ports:
      - containerPort: 80  # Corrected the field name

---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: LoadBalancer
  selector:
      tier: frontend
      purpose: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
